### ISSUE TITLE
在superset上使用报错

### ISSUE THREAD

**Issue by gangly** [deatheyes/PySnappydata#4]
你好我在superset上使用报错
用的python3.6，安装compatibility23 版本
报错信息为：
ERROR: {"error": "Connection failed!\n\nThe error message returned was:\nCan't load plugin: sqlalchemy.dialects:snappydata"}

**Comment by deatheyes** [comment]
我自己的测试没有问题，python版本 3.7.4。你那边安装过程中的信息及报错发出来看看呗~

**Comment by gangly** [comment]
> 我自己的测试没有问题，python版本 3.7.4。你那边安装过程中的信息及报错发出来看看呗~

安装完了没报错，就是在配置superset数据源的时候点击test按钮，报错
ERROR: {"error": "Connection failed!\n\nThe error message returned was:\nCan't load plugin: sqlalchemy.dialects:snappydata"}

另外根据文档上用sqlalchemy的两个例子也报错了
只有第一个例子能用

**Comment by deatheyes** [comment]
README上的例子是2.7的语法，3+需要稍微改改，比如加上括号之类的。
确认下sqlalchemy是不是装了，以及是哪个版本的python装的sqlalchemy

**Comment by gangly** [comment]
> README上的例子是2.7的语法，3+需要稍微改改，比如加上括号之类的。
> 确认下sqlalchemy是不是装了，以及是哪个版本的python装的sqlalchemy

用的python3.6，能不能给些python3的sqlalchemy使用例子  谢谢

**Comment by gangly** [comment]
`user = Table('user_c', metadata,
        Column('id', INTEGER, primary_key=True),
        Column('name', VARCHAR(20)),
    )
metadata.create_all(engine)
conn = engine.connect()

i = user.insert()
u = dict(id=0, name='yy')
r = conn.execute(i, **u)
print r.rowcount

s = select([user.c.name]).where(user.c.id==0)`
这里的user_c，user.c.name中的c是什么呢
如何指定查找某个库里面的表

**Comment by deatheyes** [comment]
c是指columns，具体可以参考这里 https://docs.sqlalchemy.org/en/13/core/metadata.html
